jupyterhub:
  cull:
    # don't cull authenticated users
    users: False
  custom:
    binderauth_enabled: true
  hub:
    baseUrl: /jupyterhub/
    # Configure authentication with external provider:
    redirectToServer: false
    services:
      binder:
        oauth_no_confirm: true
        oauth_redirect_uri: "https://<binderhub_ip>/binderhub/oauth_callback"
        oauth_client_id: "binder-oauth-client-test"
    config:
      GenericOAuthenticator:
        login_service: "ESCAPE IAM"
        client_id: "<redacted>"
        client_secret: "<redacted>"
        oauth_callback_url: "https://<binderhub_ip>/jupyterhub/hub/oauth_callback"
        authorize_url: https://iam-escape.cloud.cnaf.infn.it/authorize
        token_url: https://iam-escape.cloud.cnaf.infn.it/token
        userdata_url: https://iam-escape.cloud.cnaf.infn.it/userinfo
        userdata_method: GET
        userdata_params: {'state': 'state'}
        username_key: preferred_username
      JupyterHub:
        authenticator_class: generic-oauth
  singleuser:
    # Make notebook servers aware of hub
    cmd: jupyterhub-singleuser
    # (Optional) Configure persistent storage
    # The BinderHub Helm chart disables some default JupyterHub behaviour
    # (such as per user PVCs); we re-enable this here.
    storage:
      type: dynamic
      extraLabels: {}
      static:
        pvcName:
        subPath: "{username}"
      capacity: 10Gi
      homeMountPath: /home/jovyan/personal
      dynamic:
        storageClass: "rook-cephfs"
        pvcNameTemplate: claim-{username}{servername}
        volumeNameTemplate: volume-{username}{servername}
        storageAccessModes: [ReadWriteOnce]
      extraVolumes:
        - name: binderhub-shared-rw
          persistentVolumeClaim:
            claimName: binderhub-data-cephfs-rw-pvc
      extraVolumeMounts:
        - name: binderhub-shared-rw
          mountPath: /home/jovyan/shared-workflows
    
    # (Optional) Add default environments for JHub to offer
    profileList:
    - display_name: "Default"
      description: "The default image"
      default: true
    - display_name: "Jupyter data science notebook"
      description: "data science env"
      kubespawner_override:
        image: jupyter/datascience-notebook:latest
  auth: {}
 
# BinderHub config
config:
  BinderHub:
    # Enable auth, configured in jupyterhub section
    auth_enabled: true
    use_registry: true
    image_prefix: srcdev/binder-dev-
    hub_url: https://<binderhub_ip>/jupyterhub/
    base_url: /binderhub/
 
service:
  type: NodePort